//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimsIn
    {
        public ClaimsIn()
        {
            this.ServiceRecord = new HashSet<ServiceRecord>();
        }
    
        public System.Guid ClaimsInId { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> DownloadDate { get; set; }
        public string RecordIndex { get; set; }
        public double ClaimAmount { get; set; }
        public double PaidAmount { get; set; }
        public string Content { get; set; }
        public string ValidationContent { get; set; }
        public string SubmittedFileName { get; set; }
        public string FileSubmittedStatus { get; set; }
        public Nullable<System.DateTime> DateChangeToAccepted { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ICollection<ServiceRecord> ServiceRecord { get; set; }
    }
}
