//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimsResubmitted
    {
        public System.Guid RecordId { get; set; }
        public System.Guid UserId { get; set; }
        public int ClaimNumber { get; set; }
        public string PatientLastName { get; set; }
        public string HospitalNumber { get; set; }
        public System.DateTime ServiceDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UnitCode { get; set; }
        public int UnitNumber { get; set; }
        public string UnitPremiumCode { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
