//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimsInReturn
    {
        public ClaimsInReturn()
        {
            this.PaidClaim = new HashSet<PaidClaim>();
            this.RejectedClaim = new HashSet<RejectedClaim>();
            this.ClaimsReturnPaymentSummary = new HashSet<ClaimsReturnPaymentSummary>();
        }
    
        public System.Guid ClaimsInReturnId { get; set; }
        public System.Guid UserId { get; set; }
        public double TotalSubmitted { get; set; }
        public double TotalApproved { get; set; }
        public System.DateTime UploadDate { get; set; }
        public int RecordIndex { get; set; }
        public int TotalPaid { get; set; }
        public int TotalRejected { get; set; }
        public string ReturnFooter { get; set; }
        public string Content { get; set; }
        public double TotalPaidAmount { get; set; }
        public double TotalPremiumAmount { get; set; }
        public double TotalProgramAmount { get; set; }
        public int ReturnFileType { get; set; }
        public double OtherFeeAndPayment { get; set; }
        public string ReturnFileName { get; set; }
        public Nullable<System.DateTime> ReturnFileDate { get; set; }
        public string RunCode { get; set; }
        public string TotalLineType { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ICollection<PaidClaim> PaidClaim { get; set; }
        public virtual ICollection<RejectedClaim> RejectedClaim { get; set; }
        public virtual ICollection<ClaimsReturnPaymentSummary> ClaimsReturnPaymentSummary { get; set; }
    }
}
