//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaxDeliver
    {
        public System.Guid FaxDeliverId { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid ServiceRecordId { get; set; }
        public long TransactionId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Status { get; set; }
        public string PDFContent { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
