//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBS.DomainModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedicalBillingSystemEntities : DbContext
    {
        public MedicalBillingSystemEntities()
            : base("name=MedicalBillingSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Applications> Applications { get; set; }
        public DbSet<PaidClaim> PaidClaim { get; set; }
        public DbSet<RejectedClaim> RejectedClaim { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<UserCertificates> UserCertificates { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<UsersInRoles> UsersInRoles { get; set; }
        public DbSet<FaxDeliver> FaxDeliver { get; set; }
        public DbSet<ClaimsIn> ClaimsIn { get; set; }
        public DbSet<ClaimsInReturn> ClaimsInReturn { get; set; }
        public DbSet<UserProfiles> UserProfiles { get; set; }
        public DbSet<Memberships> Memberships { get; set; }
        public DbSet<UnitRecord> UnitRecord { get; set; }
        public DbSet<ServiceRecord> ServiceRecord { get; set; }
        public DbSet<ClaimsSearchView> ClaimsSearchView { get; set; }
        public DbSet<ClaimsResubmitted> ClaimsResubmitted { get; set; }
        public DbSet<ClaimsReturnPaymentSummary> ClaimsReturnPaymentSummary { get; set; }
    }
}
