//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitRecord
    {
        public System.Guid UnitRecordId { get; set; }
        public System.Guid ServiceRecordId { get; set; }
        public string UnitCode { get; set; }
        public int UnitNumber { get; set; }
        public double UnitAmount { get; set; }
        public string UnitPremiumCode { get; set; }
        public string ExplainCode { get; set; }
        public long RecordIndex { get; set; }
        public double PaidAmount { get; set; }
        public string DiagCode { get; set; }
        public string RunCode { get; set; }
        public string ExplainCode2 { get; set; }
        public string ExplainCode3 { get; set; }
        public string RecordClaimType { get; set; }
        public string SpecialCircumstanceIndicator { get; set; }
        public string BilateralIndicator { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public double ProgramPayment { get; set; }
        public Nullable<double> SubmittedAmount { get; set; }
        public Nullable<long> SubmittedRecordIndex { get; set; }
        public string OriginalRunCode { get; set; }
    
        public virtual ServiceRecord ServiceRecord { get; set; }
    }
}
