//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.FaxDeliver = new HashSet<FaxDeliver>();
            this.ClaimsIn = new HashSet<ClaimsIn>();
            this.ClaimsInReturn = new HashSet<ClaimsInReturn>();
            this.ServiceRecord = new HashSet<ServiceRecord>();
            this.ClaimsResubmitted = new HashSet<ClaimsResubmitted>();
            this.ClaimsReturnPaymentSummary = new HashSet<ClaimsReturnPaymentSummary>();
        }
    
        public System.Guid ApplicationId { get; set; }
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
        public bool IsAnonymous { get; set; }
        public System.DateTime LastActivityDate { get; set; }
    
        public virtual Applications Applications { get; set; }
        public virtual UserCertificates UserCertificates { get; set; }
        public virtual ICollection<FaxDeliver> FaxDeliver { get; set; }
        public virtual ICollection<ClaimsIn> ClaimsIn { get; set; }
        public virtual ICollection<ClaimsInReturn> ClaimsInReturn { get; set; }
        public virtual UserProfiles UserProfiles { get; set; }
        public virtual Memberships Memberships { get; set; }
        public virtual ICollection<ServiceRecord> ServiceRecord { get; set; }
        public virtual ICollection<ClaimsResubmitted> ClaimsResubmitted { get; set; }
        public virtual ICollection<ClaimsReturnPaymentSummary> ClaimsReturnPaymentSummary { get; set; }
    }
}
