//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfiles
    {
        public System.Guid UserId { get; set; }
        public string DoctorNumber { get; set; }
        public string DoctorName { get; set; }
        public string ClinicNumber { get; set; }
        public string DiagnosticCode { get; set; }
        public string CorporationIndicator { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string PostalCode { get; set; }
        public string PhoneNumber { get; set; }
        public string ClaimMode { get; set; }
        public string GroupNumber { get; set; }
        public string GroupUserKey { get; set; }
        public string DefaultPremCode { get; set; }
        public string DefaultServiceLocation { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
