//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimsReturnPaymentSummary
    {
        public System.Guid RecordId { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid ClaimsInReturnId { get; set; }
        public int GroupIndex { get; set; }
        public string TotalLineType { get; set; }
        public double FeeSubmitted { get; set; }
        public double FeeApproved { get; set; }
        public double TotalPremiumAmount { get; set; }
        public double TotalProgramAmount { get; set; }
        public double TotalPaidAmount { get; set; }
        public string RunCode { get; set; }
        public int LineNumber { get; set; }
    
        public virtual ClaimsInReturn ClaimsInReturn { get; set; }
        public virtual Users Users { get; set; }
    }
}
