//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCertificates
    {
        public System.Guid UserId { get; set; }
        public string CertificateEncoded { get; set; }
        public string CertificatePassKey { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
